[package]
name = "aya-co-re-issue-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
aya-co-re-issue-common = { path = "../aya-co-re-issue-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "aya-co-re-issue"
path = "src/main.rs"
